feat(rate movie): add static rating component to the movie details page
Pixelmatters/grupa-movie-app pull request #54
Opened 2020-07-08 17:35 UTC by tiagop93

Also fixed some typos.

2020-07-08 17:54 UTC, FilipeAVS requested changes

2020-07-08 17:54 UTC, FilipeAVS commented on src/components/MovieDisplay/MovieDisplay.tsx
> +            ></Rating>
You can immediately close the tag `/>`

2020-07-08 17:54 UTC, FilipeAVS commented on src/components/MovieDisplay/MovieDisplay.tsx
> +            <b> Rate:</b>
Give some space after the `:` so that the component is not glued to the text.

2020-07-08 18:04 UTC, FilipeAVS approved these changes

2020-07-08 18:05 UTC, JuniorDiasOliveira requested changes

2020-07-08 18:05 UTC, JuniorDiasOliveira commented on src/components/MovieDisplay/MovieDisplay.tsx
> +    fontSize: '20px',
Change to `rem`

2020-07-09 07:46 UTC, PedroFonseca17 approved these changes

2020-07-09 09:14 UTC, JuniorDiasOliveira approved these changes

2020-07-09 09:17 UTC, merged